version: "2"
linters:
  default: none
  enable:
    - copyloopvar
    - errcheck
    - forcetypeassert
    - goconst
    - gocritic
    - godot
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - revive
    - staticcheck
    - unused
    - whitespace
  settings:
    gocritic:
      enabled-tags:
        - performance
    gosec:
      excludes:
        - G702  # Command injection via taint (false positives in CLI/infra code)
        - G703  # Path traversal via taint (false positives in CLI/infra code)
        - G704  # SSRF via taint (false positives in CLI/infra code)
        - G705  # XSS via taint (false positives in CLI/infra code)
    lll:
      line-length: 200
    misspell:
      locale: US
    revive:
      rules:
        - name: var-naming
          disabled: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
